---
- include_tasks:        'tasks/common/user_groups.yml'
- include_tasks:        'tasks/common/users.yml'
- include_tasks:        'tasks/common/create_files.yml'
- include_tasks:        'tasks/common/install_files.yml'
- include_tasks:        'tasks/common/authorized_keys.yml'
- include_tasks:        'tasks/common/allow_users.yml'
