#!/bin/bash

# Naughty.  This should be templated and fed from inventory.
# ssh-keygen -lf inventory/hosts/aaron-phone/users/aaron/files/ssh_keys/id_rsa.pub | awk '{print $2}'
fingerprint='SHA256:RuC+F9r+4SJ5HoqnDzFGmjl3Q+7IlQFopmsvZErbsy0'
search_string="ssh2: RSA ${fingerprint}"

ssh_log_files=( $(
  ls -r /var/log/auth.log*
) )

line="$(
  for f in "${ssh_log_files[@]}"; do
    zgrep "${search_string}" "${f}"
  done \
    | tail -n 1
)"

if test '' == "$(echo ${line})"; then
  exit 1
fi

date_string="$(
  echo "${line}" \
  | awk '{print $3" "$2" "$1}'
)" \
  || exit 1

date +%s -d "${date_string}"
